server:
  port: 8081

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profiles.active@
  jackson:
    time-zone: Asia/Ho_Chi_Minh   # JSON response đúng giờ VN
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh   # Hibernate dùng đúng TZ

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenvantien2004.vinhphuc@gmail.com
    password: xspvbmbqgahlqksx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

jwt:
  secret: mysecretkeymysecretkeymysecretkey1234
  expiration: 43200000